### ISSUE TITLE
missing python version upper bound to prevent installation alongside 3.12

### ISSUE THREAD

**Issue by AaronOpfer** [conda-forge/dohq-artifactory-feedstock#5]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Upstream had been tracking Python 3.12 incompatibility for over a year.

https://github.com/devopshq/artifactory/issues/430

However, conda allows us to install python 3.12 and dohq-artifactory together.

```
$ python -c 'from artifactory import ArtifactoryPath'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/aopfer/mambaforge/envs/dohq-artifactory/lib/python3.12/site-packages/artifactory.py", line 412, in <module>
    class _ArtifactoryFlavour(pathlib._Flavour):
                              ^^^^^^^^^^^^^^^^
AttributeError: module 'pathlib' has no attribute '_Flavour'

```

### Installed packages

```shell
# packages in environment at /home/aopfer/mambaforge/envs/dohq-artifactory:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       2_gnu    conda-forge
brotli-python             1.1.0           py312h2ec8cdc_2    conda-forge
bzip2                     1.0.8                h4bc722e_7    conda-forge
ca-certificates           2024.8.30            hbcca054_0    conda-forge
certifi                   2024.8.30          pyhd8ed1ab_0    conda-forge
cffi                      1.17.1          py312h06ac9bb_0    conda-forge
charset-normalizer        3.3.2              pyhd8ed1ab_0    conda-forge
dohq-artifactory          0.8.4              pyhd8ed1ab_0    conda-forge
h2                        4.1.0              pyhd8ed1ab_0    conda-forge
hpack                     4.0.0              pyh9f0ad1d_0    conda-forge
hyperframe                6.0.1              pyhd8ed1ab_0    conda-forge
idna                      3.8                pyhd8ed1ab_0    conda-forge
ld_impl_linux-64          2.40                 hf3520f5_7    conda-forge
libexpat                  2.6.3                h5888daf_0    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc                    14.1.0               h77fa898_1    conda-forge
libgcc-ng                 14.1.0               h69a702a_1    conda-forge
libgomp                   14.1.0               h77fa898_1    conda-forge
libnsl                    2.0.1                hd590300_0    conda-forge
libsqlite                 3.46.1               hadc24fc_0    conda-forge
libstdcxx                 14.1.0               hc0a3c3a_1    conda-forge
libstdcxx-ng              14.1.0               h4852527_1    conda-forge
libuuid                   2.38.1               h0b41bf4_0    conda-forge
libxcrypt                 4.4.36               hd590300_1    conda-forge
libzlib                   1.3.1                h4ab18f5_1    conda-forge
ncurses                   6.5                  he02047a_1    conda-forge
openssl                   3.3.2                hb9d3cd8_0    conda-forge
pip                       24.2               pyh8b19718_1    conda-forge
pycparser                 2.22               pyhd8ed1ab_0    conda-forge
pyjwt                     2.9.0              pyhd8ed1ab_1    conda-forge
pysocks                   1.7.1              pyha2e5f31_6    conda-forge
python                    3.12.5          h2ad013b_0_cpython    conda-forge
python-dateutil           2.9.0              pyhd8ed1ab_0    conda-forge
python_abi                3.12                    5_cp312    conda-forge
readline                  8.2                  h8228510_1    conda-forge
requests                  2.32.3             pyhd8ed1ab_0    conda-forge
setuptools                73.0.1             pyhd8ed1ab_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
tk                        8.6.13          noxft_h4845f30_101    conda-forge
tzdata                    2024a                h8827d51_1    conda-forge
urllib3                   2.2.2              pyhd8ed1ab_1    conda-forge
wheel                     0.44.0             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h166bdaf_0    conda-forge
zstandard                 0.23.0          py312hef9b889_1    conda-forge
zstd                      1.5.6                ha6fb4c9_0    conda-forge
```

### Environment info

```shell
$ conda info

     active environment : dohq-artifactory
    active env location : /home/aopfer/mambaforge/envs/dohq-artifactory
            shell level : 1
       user config file : /home/aopfer/.condarc
 populated config files : /etc/conda/condarc
                          /home/aopfer/.condarc
          conda version : 24.5.0
    conda-build version : not installed
         python version : 3.10.14.final.0
                 solver : libmamba (default)
       virtual packages : __archspec=1=zen3
                          __conda=24.5.0=0
                          __cuda=12.2=0
                          __glibc=2.36=0
                          __linux=6.9.10=0
                          __unix=0=0
       base environment : /home/aopfer/mambaforge  (writable)
      conda av data dir : /home/aopfer/mambaforge/etc/conda
  conda av metadata url : None
           channel URLs : http://lxc-nginx-internal.lan/conda/conda-forge/linux-64
                          http://lxc-nginx-internal.lan/conda/conda-forge/noarch
          package cache : /home/aopfer/mambaforge/pkgs
                          /home/aopfer/.conda/pkgs
       envs directories : /home/aopfer/mambaforge/envs
                          /home/aopfer/.conda/envs
               platform : linux-64
             user-agent : conda/24.5.0 requests/2.31.0 CPython/3.10.14 Linux/6.9.10+bpo-amd64 debian/12.7 glibc/2.36 solver/libmamba conda-libmamba-solver/24.1.0 libmambapy/1.5.8
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```

**Comment by AaronOpfer** [comment]
Reviewing the commit history suggests that Python 3.11 did not work correctly either until 0.9.1. However, since that bug only affects a subset of all features, I don't think we should restrain on it. (This would also break my pipeline if we did, since I am currently using Python 3.11 and dohq-artifactory together).

**Comment by ewu63** [comment]
Addressed by #1.
